module.exports = `
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNNN=NNN==MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNN:N        N:N=MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSON=:NN                 NN=MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNNN:          N:NNNNN::N    :=MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSON
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNN=:        NN=MYZAP-FLOWN=NN   :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOW=N=N        MYZAP-FLOWNIEDSONN=:  :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOW N        :=NIEDSONNN=====NNNNNN=N MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNN
MYZAP-FLOWMYZAP-FLOWNIEDSONN= NN       :MYZAP-FLOW N:::N :=NNNNN: :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNN
MYZAP-FLOWMYZAP-FLOWNIEDSONN:         NIEDSONN=MYZAP-FLOWNNN=NNNN: =MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNN
MYZAP-FLOWMYZAP-FLOWNIEDSON=          =NIEDSON NNN=NIEDSONN: =MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONN
MYZAP-FLOWMYZAP-FLOWNIEDSONN         :NIEDSON :NN: :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONN
MYZAP-FLOWMYZAP-FLOWNIEDSON:         NIEDSONN =NNN NIEDSONNN= =MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSON
MYZAP-FLOWMYZAP-FLOWNIEDSON:         =NIEDSON NNN=NN=NIEDSON= NNNNN=MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNN
MYZAP-FLOWMYZAP-FLOWNIEDSONN        NIEDSONN= =NNNN: :NNN:NNN =MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSON
MYZAP-FLOWMYZAP-FLOWNIEDSONN        MYZAP-FLOWNNNNNN=NNNNNN=N:NNNNN::MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWN
MYZAP-FLOWMYZAP-FLOWNIEDSON:         NIEDSONNN =MYZAP-FLOWNN:MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONNN
MYZAP-FLOWMYZAP-FLOWNIEDSON=         MYZAP-FLOWN::N=NN==MYZAP-FLOW= :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWN
MYZAP-FLOWMYZAP-FLOWNIEDSONN:         :NNNNNN N:NN:NNNNN:=NNNNN=:N: :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOW         N=NNN=MYZAP-FLOWNIEDSONN     =MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWN
MYZAP-FLOWMYZAP-FLOWNIEDSONNN=N          MYZAP-FLOWNIEDSON=N=N     MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOW=N          N=MYZAP-FLOWN=NN::      MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWN=N            N:NNNNN:NN          MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNN                             N=MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNN=:                         MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONNN                    :MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOW
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNIEDSONNN=N:N            N:MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNN=NIEDSON==MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWNNNNNN
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOW
MYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOWMYZAP-FLOW
`;