FROM debian
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/src/app

RUN mkdir /Myzap

COPY /src /Myzap/src

COPY package.json /Myzap/

COPY dialogflow.json /usr/src/app/Myzap/src/dialogflow.json

ENV MODE=PRODUCTION

#Mongo Link
ENV MONGO=mongodb://localhost:27017/myzap-db

#Idioma do BOT
ENV LANGUAGE_CODE=pt-BR

#Token para o webhook
ENV TOKENDialogflow=eb68ebf61f2dc69f3eb084531bb5dc52

#Segredo do JWT:
ENV SECRET=86d0f103bf15d37ebb1f5a23a1a4dd06

#Intent que redireciona o usuário para o modo de atendimento ao cliente
ENV INTENT_SAC=Atendimento

#Seviço de NODEMAILER
ENV USER_MAIL=

ENV PASSWORD_MAIL=

ENV SERVICE_MAIL=

#Define qual engine usar: VENOM - WPPCONNECT
ENV ENGINE=VENOM

EXPOSE 3000

RUN apt-get update && apt-get install -y \
    wget \
    build-essential libssl-dev \
    git \
    nodejs\
    npm 

RUN npm install -g n \
    && n stable 

RUN npm install -g pm2 \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm -rf google-chrome-stable_current_amd64.deb 

RUN cd /usr/src/app/Myzap/ \
    && npm install \
    && chmod 777 src/*

CMD pm2-runtime start Myzap/src/index.js  

