FROM debian
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/src/app

ENV MODE=PRODUCTION

#Mongo Link
ENV MONGO=mongodb://localhost:27017/myzap-db

#Idioma do BOT
ENV LANGUAGE_CODE=pt-BR

#Token para o webhook
ENV TOKENDialogflow=

#Segredo do JWT:
ENV SECRET=

#Intent que redireciona o usuário para o modo de atendimento ao cliente
ENV INTENT_SAC=Atendimento

#Seviço de NODEMAILER
ENV USER_MAIL=

ENV PASSWORD_MAIL=

ENV SERVICE_MAIL=

#Define qual engine usar: VENOM - WPPCONNECT
ENV ENGINE=VENOM

#CONFIGURAÇÕES DO DIALOGFLOW
ENV PROJECT_ID=""
ENV PRIVATE_KEY_ID=""
ENV PRIVATE_KEY=""
ENV CLIENT_EMAIL=""
ENV CLIENT_ID=""
ENV CLIENT_X509_CERT_URL=""

EXPOSE 3000

RUN apt-get update && apt-get install -y \
    wget \
    build-essential libssl-dev \
    git \
    nodejs\
    npm 

RUN npm install -g n \
    && n stable 

RUN npm install -g pm2 \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm -rf google-chrome-stable_current_amd64.deb 

RUN cd /usr/src/app/ \
    && git clone https://github.com/NiedsonEmanoel/Myzap \
    && cd Myzap/ \
    && npm install \
    && chmod 777 src/* 

CMD cd Myzap/ \
    && npm ci \
    && pm2-runtime src/index.js

