name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Olá! descreva sua issue e lhe atenderemos o mais rápido possível'
        pr-message: 'Ótimo que você quer contribuir, obrigado!'
